
---

- name: Installing Base tools
  zypper:
    state: latest
    name:
      - chrony
      - ansible
      - openvpn
      - git
      - neofetch
      - sshfs
      - ccrypt
      - fping
      - sudo
      - flatpak
      - cryfs
      - pwgen
      - tree
      - tmux
      - scrot
      - mc
      - wavemon
      - htop
      - fzf
  when: install_base

