
---

- name: Installing base tools
  zypper:
    state: latest
    name:
      - chrony
      - ansible
      - openvpn
      - git
      - neofetch
      - libnotify-tools
      - sshfs
      - ccrypt
      - fping
      - sudo
      - flatpak
      - cryfs
      - pwgen
      - tree
      - tmux
      - scrot
      - mc
  when: install_base

