
---

- name: Installing LXQT desktop environment
  shell: |
    zypper -n in --type=pattern lxqt
  when: install_desktop

- name: Installing desktop utilities
  zypper:
    state: latest
    name:
      - lightdm-slick-greeter-branding-openSUSE
      - lxde-common-branding-openSUSE
      - virt-manager
      - NetworkManager
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - blueman
      - owncloud-client
      - owncloud-client-dolphin
      - syncthing
      - qsyncthingtray
      - keepassxc
      - torbrowser-launcher
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-spice
      - remmina-plugin-vnc
      - remmina-plugin-xdmcp
      - remmina-plugins-gnome
      - transmission-qt
      - kwrite
      - ktimer
      - konsole
      - filelight
      - ksysguard5
      - qpdfview
      - gtk2-metatheme-numix
      - gtk3-metatheme-numix
      - breeze5-wallpapers
      - paper-icon-theme
      - origami-icon-theme
      - lxrandr
      - kcalc
      - dolphin
      - upower
      - zeal
      - krita
      - zim
  when: install_desktop_utils

- name: Installing Fonts
  zypper:
    state: latest
    name:
      - ubuntu-fonts
      - google-droid-fonts
      - kde-oxygen-fonts
      - liberation-fonts
      - lato-fonts
  when: install_desktop
  
- name: Installing Office tools
  zypper:
    state: latest
    name:
      - kmymoney
      - libreoffice-base
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-gtk3
      - odt2txt
  when: install_office_tools

- name: Increasing window handler in default theme
  lineinfile:
    path: /usr/share/themes/Numix/openbox-3/themerc
    regexp: '^window.handle.width'
    line: 'window.handle.width: 6'
  when: install_desktop

- name: Copying wallpaper files
  copy:
    src: "{{ item }}"
    dest: /usr/share/wallpapers/
  with_fileglob:
    - ./files/wallpapers/*
  when: install_desktop


