
---

  - name: Installing base tools
    zypper:
      state: latest
      name:
        - chrony
        - ansible
        - openvpn
        - git
        - neovim
        - nodejs10    # Needed for NeoVIM Coc plugin
        - neofetch
        - sshfs
        - ccrypt
        - fping
        - sudo
        - flatpak
        - cryfs
        - pwgen
        - tree
        - tmux

  - name: Installing LXQT desktop environment
    shell: zypper -n in --type=pattern lxqt

  - name: Installing desktop utilities
    zypper:
      state: latest
      name:
        - lightdm-slick-greeter-branding-openSUSE
        - lxde-common-branding-openSUSE
        - virt-manager
        - NetworkManager
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome
        - picom
        - blueman
        - owncloud-client
        - owncloud-client-dolphin
        - syncthing
        - qsyncthingtray
        - keepassxc
        - torbrowser-launcher
        - remmina
        - remmina-plugin-rdp
        - remmina-plugin-spice
        - remmina-plugin-vnc
        - remmina-plugin-xdmcp
        - remmina-plugins-gnome
        - transmission-qt
        - kwrite
        - ktimer
        - konsole
        - filelight
        - ksysguard5
        - qpdfview
        - gtk2-metatheme-numix
        - gtk3-metatheme-numix
        - breeze5-wallpapers
        - paper-icon-theme
        - origami-icon-theme
        - lxrandr
        - kcalc
        - dolphin
        - upower
        - zeal
        - gimp

  - name: Installing Fonts
    zypper:
      state: latest
      name:
        - ubuntu-fonts
        - google-droid-fonts
        - kde-oxygen-fonts
        - liberation-fonts
        - lato-fonts

  - name: Installing Office tools
    zypper:
      state: latest
      name:
        - kmymoney
        - libreoffice-base
        - libreoffice-writer
        - libreoffice-calc
        - libreoffice-draw
        - libreoffice-gtk3
        - odt2txt
    when: install_officetools == "yes"

  - name: Copying wallpaper files
    copy:
      src: "{{ item }}"
      dest: /usr/share/wallpapers/
    with_fileglob:
      - ./files/wallpapers/*



