
---

- name: OpenSUSE Leap
  set_fact:
    distro: opensuse-leap
  when: ansible_distribution == "openSUSE Leap"

- name: OpenSUSE Tumbleweed
  set_fact:
    distro: opensuse-tw
  when: ansible_distribution == "openSUSE Tumbleweed"

- include_tasks: ./base.yml
- include_tasks: ./desktop.yml
- include_tasks: ./{{ distro }}.yml
- include_tasks: ./lightdm.yml
- include_tasks: ./skel.yml
- include_tasks: ./updater.yml
- include_tasks: ./system.yml
- include_tasks: ./user.yml

