
---

- name: Leap specific packages
  zypper:
    state: latest
    name:
      - compton
      - compton-conf
      - ruby2.5-rubygem-asciidoctor
  when: install_desktop_utils

- name: Removing MozillaFirefox
  zypper:
    state: absent
    name:
      - MozillaFirefox
  when: install_desktop_utils

